### ISSUE TITLE
Error when calling module_stability 

### ISSUE THREAD

**Issue by HASaunders** [almeidasilvaf/BioNERO#7] opened 2023-05-10 15:40 UTC
When calling `module_stability`, I get the following error:

> Error in .plotOrderedColorSubplot(order = order, colors = colors, rowLabels = rowLabels,  : 
>   Length of colors vector not compatible with number of objects in 'order'.

As I understand this is because maxBlockSize needs to be raised: see issue [here](https://bioinformatics.stackexchange.com/questions/8816/error-code-in-wgcna-dealing-with-large-data-sets-block-wise-network-constructi). Would be great if this could be added as an option to `module_stability`. 

Thanks in advance.

**Comment by almeidasilvaf** [comment] 2023-05-11 16:57
Hi, @HASaunders 

Thank you for using __BioNERO__.

It seems like this bug has been fixed by WGCNA developers (see [this change here](https://github.com/cran/WGCNA/blob/31f538c2f9d7d48f35f7098b4effe17331357d0d/Changelog#L14-L17)). There is no `maxBlockSize` parameter anymore.

Could you update your BioNERO version (and WGCNA too, maybe) to the latest version and run `module_stability()` again to see if the problem is solved? That would be BioNERO 1.8.0 and WGCNA 1.71. You might also have to update your R version. As you forgot to include your session info with packages and versions you used, I cannot know what else you need to update.

If that solves your problem, feel free to close the issue.

Best,
Fabricio

**Closed as completed** 2023-05-25 07:25 UTC
