### ISSUE TITLE
Can the color of dendro be adjusted by myself?

### ISSUE THREAD

**Issue by Tang-pro** [almeidasilvaf/BioNERO#23] opened 2024-04-25 08:03 UTC
Hi, @almeidasilvaf 
A very useful tool, but this color does not meet my requirements. I am using plot_dendro_and_colors, how can I adjust it to the color I want?
And plot_ngenes_per_module?

**Comment by almeidasilvaf** [comment] 2024-05-03 09:18
Hi, @Tang-pro 

This is a duplicate of https://github.com/almeidasilvaf/BioNERO/issues/1. See the referenced issue for details on how to solve this.

Best,
Fabricio

**Closed as completed by almeidasilvaf** 2024-05-03 09:18 UTC
