### ISSUE TITLE
GCN Color By Issue

### ISSUE THREAD

**Issue by LMee17** [almeidasilvaf/BioNERO#2] opened 2022-04-19 10:02 UTC
Greetings

Firstly, BioNERO is fantastic. Thank you for writing such a useful package.

I'm having an issue when I'm attempting to colour my networks by custom annotations. Using below; 

```
plot_gcn(edgelist_gcn = edges_filtered, 
         net = net,
         color_by = myann,
         hubs = hubs)
```

gives me a complete network with the correct number of annotations in the legend, however, upon closer inspection I've noticed that some of the hub genes are not coloured correctly and therefore I assume the rest of the network may be similarly jumbled. The object myann is a two-column data frame with Genes | Annotation. 

All genes match those in the edges_filtered, net and hubs objects. Annotation is either Background / Immune

Any suggestions welcome

Best
Lauren

**Comment by almeidasilvaf** [comment] 2022-04-19 11:47
Hi, @LMee17 

Thank you very much for your feedback!

What do you mean by "not coloured correctly"? 

Could you share your data so I can try to reproduce the error on my end? Maybe you can save your objects as an .rda file (xz-compressed) and put it in a repository.

**Comment by LMee17** [comment] 2022-04-19 12:33
My net object, even after compression, is too large to upload to GitHub ...


By "not coloured" correctly, I mean that if the legend says that "Immune" genes are coloured red and another function coloured green, a hub gene may be coloured one but actually annotated the other.  I've tried to attach an example below. Four out of the 5 labelled hub genes were annotated "Background", and one (LOC106792914) "Putative Immune". This plot suggests LOC106792914 is a background gene, and designated LOC106785447 as "Unknown", which is incorrect. 

![GCN_annotated](https://user-images.githubusercontent.com/36163079/164003251-94c8778e-a73a-4200-bb01-d869c8a49472.png)

This is of course assuming that each gene is supposed to match my annotations and I'm not misinterpreting the plot somehow. 

Are there any troubleshooting methods you could suggest that I could try? I have already tried ensuring the data frame is factor only, removing and adding column names, reducing the annotation file to only the genes found within that module, and continue to get the mismatch. 

If not I will make a smaller dataset to test when I have the chance. 

Best wishes (and thanks for such a speedy response)

Lauren

**Comment by almeidasilvaf** [comment] 2022-04-19 15:27
That's odd. Have you checked if you don't have multiple annotations for the same gene? For example:

|Gene | Annotation |
|----|----|
| GeneA | Function 1 |
| GeneA | Function 2 |

The network object is large due to the adjacency and correlation matrices. For `plot_gcn()`, only the elements `genes_and_modules` and `kIN` are used. Could you filter your network object to only contain these elements and share the data you're using to plot? This could be done as follows:

```r
fnet <- net[c("kIN", "genes_and_modules")]
```

You can save `fnet` and all objects you are using for plotting (including `edges_filtered`, `myann` and `hubs`) using `save()` with `compress = "xz"` and upload them to a repo I can access.

**Comment by LMee17** [comment] 2022-04-20 06:59
I'd already checked for duplicate genes, unfortunately that wasn't the problem

Yes that filtering helped quite considerably ! You can find my data object here https://github.com/LMee17/BioNEROFix

Thanks!

**Comment by almeidasilvaf** [comment] 2022-04-21 11:39
Hi, @LMee17 

Thank you for sharing the data. I found what was causing the problem and fixed it. 

Could you please reinstall the devel version of the package from GitHub and confirm that everything works fine for you now? You can install it with:

```r
remotes::install_github("almeidasilvaf/BioNERO")
```

**Comment by LMee17** [comment] 2022-04-22 07:38
Hi @almeidasilvaf 

Yes! That's fixed it!

Thank you so much for your time!

**Comment by almeidasilvaf** [comment] 2022-04-22 08:34
Great to know it worked! I'll close this issue, then.

Thank you for your contribution.

**Closed as completed by almeidasilvaf** 2022-04-22 08:34 UTC
