### ISSUE TITLE
inconsistency merged colors/genes_cmodules with consMEs modules

### ISSUE THREAD

**Issue by daniaodeh** [almeidasilvaf/BioNERO#11] opened 2023-07-05 09:49 UTC
Hi, 
I noticed that column names in consMEs, supposedly the merged colors, aren't consistent with merged colors in the result of consensus_modules function, but they are the same as the unmerged ones. 
can you tell me why? and which ones to use ?

Thanks :)

**Comment by almeidasilvaf** [comment] 2023-07-09 13:01
Hi, @daniaodeh 

Thank you for using __BioNERO__. 

I can't reproduce this issue with the example data set that comes with the package. Could you share a reproducible example (using [reprex](https://reprex.tidyverse.org/))?

If you could also describe in more details what you want to do, it'd be easier for me to help with your particular case.


Best,
Fabricio

**Comment by daniaodeh** [comment] 2023-07-18 13:29
Hey again :)
I simply want to use the merged modules and find the genes in each merged module. 
If I use genes_cmodules, the colors I find don't match 'validColors' in consMEs data or the column names of the consMEs data.
I encountered with this problem ,when used consMEs and correlated them with traits, but when tried to plot number of genes in each module using genes_cmodules I noticed the modules names aren't the same.

 ```r
consensus <- consensus_modules(zma_list, power = powers, cor_method = "pearson")

# merged modules that are assigned to genes.    
sort(unique(consensus$genes_cmodules$Cons_modules))
#> [1] "cyan"         "grey60"       "lightcyan"    "lightgreen"   "lightyellow" 
#> [6] "midnightblue" "salmon"

# merged modules 
sort(unique(consensus$dendro_plot_objects$Merged))
#> [1] "cyan"         "grey60"       "lightcyan"    "lightgreen"   "lightyellow" 
#> [6] "midnightblue" "salmon"

# modules colors in consMEs sets
sort(unique(consensus$consMEs$set2$validColors) )
#> [1] "black"      "brown"      "green"      "grey"       "lightcyan" 
#> [6] "lightgreen" "magenta"
sort(unique(consensus$consMEs$set1$validColors) )
#> [1] "black"      "brown"      "green"      "grey"       "lightcyan" 
#> [6] "lightgreen" "magenta"
sort(gsub('ME','',colnames(consensus$consMEs$set2$data) )
)
#> [1] "black"      "brown"      "green"      "grey"       "lightcyan" 
#> [6] "lightgreen" "magenta"

```

**Comment by almeidasilvaf** [comment] 2023-08-21 07:04
Hi, @daniaodeh 

Sorry for taking so long to look into this issue (I was on vacation when you opened the issue).

There was indeed a recently introduced bug in `consensus_modules()`. Basically, this function was returning unmerged module names in the element *genes_cmodules*, which led to inconsistencies between *genes_cmodules* and *consMEs*. 

The bug has now been fixed in the latest version.

Thank you for contributing!

Best,
Fabricio

**Closed as completed by almeidasilvaf** 2023-08-21 07:04 UTC
Labels: question
